### ISSUE TITLE
Wombat and banners always active in proxy mode

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#107]
It is not always desirable to have wombat running and banners inserted during playback in proxy mode:

- Collection is accessed locally and should look as much as the original as possible
- Collection is accessed via emulator/legacy browser that is not able to handle the javascript

In these cases it is desirable to have wombat and banners running in proxy mode:

- reconstructing video captures
- reconstructing video captures on contemporary browsers emulated in the future

In these cases it is desirable to run different banners/scripts in proxy mode:

- different augmentation needs during proxy playback (emojis yes, banners no)
- running adapted scripts for legacy browsers

**Suggestion:**
For each collection, introduce more settings for `proxy_options` in  `config.yaml`:

```yaml
proxy_options:
    use_wombat: true
    use_banners: false
```

If the directory `templates` contains a file named `banner_proxy.html`, in will be preferred over `banner.html` in proxy mode.

If a collection in proxy mode uses a banner but no wombat, the banner has to take care of inserting itself and other things completely.

**Comment by ikreymer** [comment]
Added `use_banner` (enable banner head insert) and `use_client_rewrite` (enable wombat/client side rewriting) options which can be set to True/False.. Note that client rewrite requires the banner insert to be enabled.

Rather than having a separate file for proxy mode, the `banner_html` file can use a template conditional:
`{% if wbrequest.options.is_proxy %}` to support custom banner for proxy mode, allowing for more flexibility.
