### ISSUE TITLE
Regression: embedded vimeo videos not replayed anymore

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#126]
http://webenact.rhizome.org/v4ult/20150421174036/http://v4ult.cc/the-draining-of-the-mesopotamian-marshes-of-iraq/

When clicking on "intervention 2" on the top right, a sub-page with embedded vimeo clips shows up. They are not rewritten correctly anymore apparently and show up as black rectangles.

pywb 0.10.6

collection re-indexed

**Comment by ikreymer** [comment]
Think I see what happened.. due to rewriting issues earlier, HTML5 Vimeo was being converted to flash, and so the flash replacement was kicking in. However, due to a fix in wombat, the correct HTML5 replacement is now happening.. But, a html5 player.js file is missing (because it was not recorded as html5) so it doesn't even get to create the html5 `<video>` tag and errors out before.. 
This is tricky because its not getting to the point of video loading, and I don't want to undo the rewriting fix to make it do flash again (now it correctly record html5 video player).. Can you send me the WARC and I'll see I can fix with special case? Of course, easiest solution is to rerecord, and you'd get the HTML5 vimeo player

**Comment by despens** [comment]
In this case, re-recording is possible. Lucky :smile:

**Comment by ikreymer** [comment]
This'll affect vvork, other use cases as well, so need to address it.
