### ISSUE TITLE
Large PDF with 206 Partial Content responses.

### ISSUE THREAD

**Issue by jcushman** [ikreymer/pywb#144]
I'm having trouble playing back this PDF on Perma or Webrecorder:

http://scholar.princeton.edu/sites/default/files/oversize_pdf_test_0.pdf

It's a 100MB pdf that results in about 100 responses with status code `206 Partial Content`.

When I play it back on Perma, it keeps loading data forever -- I think the CDX is failing to identify the correct part to play back because they're all under the same URL. When I try to record on webrecorder the recording fails.

Any tips on this before I debug further? Thanks!

**Comment by ikreymer** [comment]
With webrecorder, it should handle this similar to video, in that only the first 206 starting with 0- should trigger a recording, while the rest should not be recorded, resulting in one full copy on the file.. This is a good non-video test case, so will see what's happening..

If the file is recorded in pieces, than it becomes very difficult to replay.. since replay ranges may be different than recording ranges.. If it is one file, it should be able to play it back by cacheing it and applying range requests on the cached version..

**Comment by ikreymer** [comment]
It does record on Webrecorder, though UI is not updated, because its not a page.. but if you switch to Replay mode, you'll see that it has been recorded, and the WARC is available for download..
It also appears that, at least in Chrome, even though it does range requests, the pdf viewer does not update until the full thing is loaded.

**Comment by ikreymer** [comment]
Not sure what else can be done here.. First, ensure that the file has been archived as a single chunk, and if there are still replay issues in Perma, can take a look at the specific example. pywb should properly handle the 206 responses.
