### ISSUE TITLE
Many monkey-patched DOM accessors broken in Safari when live rewriting is enabled

### ISSUE THREAD

**Issue by robertknight** [ikreymer/pywb#147]
Many DOM accessors that are monkey-patched by `wombat.js` are broken in Safari where fetching the original getter/setter implementations using either `__lookupGetter__` or `Object.getOwnPropertyDescriptor()` does not work. See https://github.com/hypothesis/via/issues/59 and https://bugs.webkit.org/show_bug.cgi?id=140575

---

**Update**: In Safari 9, Object.getOwnPropertyDescriptor() for native DOM properties returns a descriptor object but the getter, setter and configurable bits are incorrect. In particular, the getter and setter are undefined. See the upstream bug at https://bugs.webkit.org/show_bug.cgi?id=49739#c19 for discussion.

**Comment by robertknight** [comment]
See also - http://stackoverflow.com/questions/992461/is-it-possible-to-override-document-cookie-in-webkit

**Comment by ikreymer** [comment]
Thanks, yeah, I think we need to update wombat.js to gracefully degrade for browsers that do not support all the overrides...

**Comment by robertknight** [comment]
This error also appears to be affecting Edge as well: https://github.com/hypothesis/via/issues/55

**Comment by ikreymer** [comment]
Ok, well that's good to know that this is all related.. I was focusing on Chrome and FF, but clearly need to test other browsers, and even if rewriting won't work, it should avoid these errors..

**Comment by robertknight** [comment]
I'm looking into the possibilities for detecting the browser limitations that prevent the current approach to JS rewriting. There don't appear to be any tests that exercise wombat.js' rewriting functionality at present. Is this correct or did I miss something?

**Comment by ikreymer** [comment]
Yes, you are correct, unfortunately, there is not a client-side test suite yet.. it is high on my list of priorities, I would be happy to collaborate on building one.. Do you have any suggestions? I was thinking of using: https://splinter.readthedocs.org/en/latest/ with Selenium..

**Comment by robertknight** [comment]
My main priority at the moment is end-to-end testing of Via, for which I was planning to start with either Selenium or possibly the WebDriver clients (eg. chromedriver) directly. We're considering using Sauce Labs or BrowserStack for cross-browser testing.

In the process of setting that up I'll no doubt learn a lot that might come in useful for testing pywb. I can't promise how much time I'd have to help with that directly.

What is the best documentation available about what `wombat.js` does, how it works etc. besides the code itself?

**Comment by ikreymer** [comment]
That's basically it, sorry to say.. I just haven't had time to document it further, and its been somewhat experimental for a long time, but maybe now is the time to improve documentation/testing..

There's also `vidrw.js` which is specifically concerned with video rewriting, mentioned in the Video wiki page, however, that is not as relevant for Via.

Yes, I think WebDriver is the way to go (Splinter is just a wrapper that abstracts out configuring individual webdrivers)

I'd be happy to help/coordinate and maybe certain tests I can move into pywb itself as well, since there'll be overlap.

**Comment by robertknight** [comment]
I found your presentation at http://netpreserve.org/sites/default/files/attachments/2015_IIPC-GA_Slides_12_Kreymer.ppt which was a useful high-level introduction.

**Comment by ikreymer** [comment]
Ah yes, I forgot about that! Heh, glad that this was useful :)

**Comment by robertknight** [comment]
I've started some work on this in https://github.com/robertknight/pywb/tree/rewriting_proxy_e2e_tests

**Comment by ikreymer** [comment]
Awesome! I will have some time next week to take a look in detail

**Comment by robertknight** [comment]
I'm currently sketching an email to the rest of the Hypothesis team about how we tame Via, with a focus on avoiding regressions and detecting problems in the wild.

There are several things that I think can be done with the client-side code to facilitate this:

1. Clearly define the interface between `wombat.js` and the web service, so that it can be hosted in a test harness or replaced/modified as necessary.
2. Break up the client-side code (especially `wombat.js`) into smaller pieces that can be tested more easily and that allow switching between different implementations depending on the browser's capabilities.
3. Add hooks in `wombat.js` that can be used to inject monitoring for reporting client-side errors.

At the moment it is partly an open question whether we'll continue to use/develop Wombat in H or whether it would be better replaced by an alternative implementation - given that we _think_ we can get by with lighter rewriting. Something that might affect this decision is licensing. `pywb` is currently GPLv3-licensed whereas the rest of H is BSD-2. That might be a problem for us in future given that we have partners who want to either run their own instances of H's services or at least be sure that they can, possibly with modifications. If there is a possibility of reconsidering the licensing for the client JS that would be useful to know.

**Comment by ikreymer** [comment]
Thanks for the update.. I think this need not be as complicated, I was imagining two things:
1) Add flags to disable certain rewrite options in the config directly -- this is already done for certain things with the various `wb_opts.skip_*` flags, but can be made more consistent.

2) If an override is active but fails, just catch the exception and report/track the failure so that it could be verified. The test harness could then have the per-browser feature matrix and verify it against wombat. eg. it could know that cookie override is not available in Safari, and verify that it has in fact failed while testing..

I would hope that you can continue to use wombat for several reasons:
 - The browser issues need to be solved anyway for web archives to work better in Safari, Edge, IE, etc..
 - There will likely be a use case combining web archives with annotation, which will need the full rewriting capability when it is available..

As for the license, I have been considering switching pywb to an Apache license in the future.. Would that alleviate your concerns?

**Comment by robertknight** [comment]
> I would hope that you can continue to use wombat for several reasons:

Likewise.

> As for the license, I have been considering switching pywb to an
> Apache license in the future.. Would that alleviate your concerns?

IANAL and all that, but I'm fairly sure it would.

**Comment by ikreymer** [comment]
Fixed by: 520811729924b719746613f3545e3d0fc15c29d1
