### ISSUE TITLE
cdx-server json output

### ISSUE THREAD

**Issue by atomotic** [ikreymer/pywb#199]
this [spec](https://github.com/internetarchive/wayback/blob/master/wayback-cdx-server/README.md#output-format-json) describe the json output of a cdx server as an array of arrays.

pywb cdx-server return a list of hashes (eg. from [commocrawl](http://index.commoncrawl.org/CC-MAIN-2016-40-index?url=http%3A%2F%2Fwww.repubblica.it&output=json)) that is not a valid json.
could be better return a valid array of hashes?

**Comment by atomotic** [comment]
i solved this way, not very elegant...
https://github.com/ikreymer/pywb/blob/master/pywb/cdx/cdxops.py#L57-L59

```
def cdx_to_json(cdx_iter, fields):
    yield "["
    for i, cdx in enumerate(cdx_iter):
        if i: yield "," + cdx.to_json(fields)
        else:  yield cdx.to_json(fields)
    yield "]"
```

**Comment by ikreymer** [comment]
Yes, this is by design, and is a change from the original wayback cdx spec. The reason is that it is much easier to process one line at time this way, especially for large data sets. Otherwise, the entire response must be read into memory at once. Perhaps I should update the docs to indicate the response is NDJSON (http://ndjson.org/)

**Comment by atomotic** [comment]
ok ok, seems a right solution. i was not aware of ndjson spec.
thanks
