### ISSUE TITLE
Would like custom port

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#60]
Pywb always runs on port 8080, I'd like to be able to change that via config.yaml and/or a command line parameter.

**Comment by ikreymer** [comment]
The 8080 port is only configured this way for the WSGI ref implementation.
Different WSGI containers will specify the port in a different way, so there is no one way to place it.

However, perhaps there's a better way to specify the port for the 'default' cli interface, so leaving this open as a reminder to think about that.

**Comment by ikreymer** [comment]
In 0.9.0, formalizing the cli interface for `wayback` tool so that the port will be selectable via command line: `wayback -p ...` Also switching to waitress wsgi server instead of wsgiref as default WSGI server.

(Running with other WSGI servers would require specifying port in their respective config)

**Comment by ikreymer** [comment]
Released in 0.9.0!
